server:
  port: 8081
  
spring:
  application:
     name: alfa-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

logging:
  level:
    '[org.springframework.core.io.support]': DEBUG
    '[org.springframework.context.annotation]': DEBUG      